version: "3.3"

services:
  backend:
    container_name: choose_one_backend
    build: ./backend
    restart: always
    ports:
      - "3030:5000"
    environment:
      FLASK_DEBUG: "on"
      FLASK_APP: ./app.py
      DB_NAME: choose_one
      DB_USER: bob
      DB_PASSWORD: bob
      DB_HOST: choose_one_database
      DB_PORT: 3306
    volumes:
      - ./backend:/app
    networks:
      - backend
    depends_on:
      - database

  database:
    container_name: choose_one_database
    image: arm64v8/mysql:oracle
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "32000:3306"
    environment:
      MYSQL_DATABASE: choose_one
      MYSQL_USER: bob
      MYSQL_PASSWORD: bob
      MYSQL_ROOT_PASSWORD: bobo
    volumes:
      - ./database:/docker-entrypoint-initdb.d/:ro
    networks:
      - backend

networks:
    backend:

volumes:
    database:
    backend: